baseurl = "/"
languageCode = "de-at"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "PaperMod"
pagination.paperSize = 5
defaultContentLanguage = "de"

[params]
    # dir name of your main content (default is `content/posts`).
    # the list of set content will show up on your index page (baseurl).
    contentTypeName = "posts"

    # Add robotsNoIndex parameter to prevent search engine indexing
    robotsNoIndex = true


    # if you set this to 0, only submenu trigger will be visible
    showMenuItems = 2

    # show selector to switch language
    showLanguageSelector = false

    # set theme to full screen width
    fullWidthTheme = false

    # center theme with default width
    centerTheme = true

    # if your resource directory contains an image called `cover.(jpg|png|webp)`,
    # then the file will be used as a cover automatically.
    # With this option you don't have to put the `cover` param in a front-matter.
    autoCover = true

    # set post to show the last updated
    # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
    showLastUpdated = false

    # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
    updatedDatePrefix = "Aktualisiert am"

    # whether to show a page's estimated reading time
    # readingTime = false # default

    # whether to show a table of contents
    # can be overridden in a page's front-matter
    # Toc = false # default

    # set title for the table of contents
    # can be overridden in a page's front-matter
    TocTitle = "Inhalt"


    # [params.twitter]
    #   # set Twitter handles for Twitter cards
    #   # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
    #   # do not include @
    #   creator = ""
    #   site = ""

    [languages]
        [languages.de]
            languageName = "Deutsch"
            title = "SOPK Mitschriften"

        [languages.de.params]
            subtitle = "Meine Mitschriften für SOPK"
            owner = "Benjamin Hartmann"
            keywords = ""
            copyright = "© 2025 Benjamin Hartmann"
            menuMore = "Mehr anzeigen"
            readMore = "Mehr lesen"
            readOtherPosts = "Andere Beiträge lesen"
            newerPosts = "Neuere Beiträge"
            olderPosts = "Ältere Beiträge"
            missingContentMessage = "Seite nicht gefunden..."
            missingBackButtonLabel = "Zurück zur Startseite"
            minuteReadingTime = "min Lesezeit"
            words = "Wörter"

        [languages.de.params.logo]
            logoText = "SOPK Mitschriften"
            logoHomeLink = "/"

        [languages.de.menu]
            [[languages.de.menu.main]]
                identifier = "about"
                name = "Über diese Seite"
                url = "/about"
                # [[languages.de.menu.main]]
                #   identifier = "showcase"
                #   name = "Showcase"
                #   url = "/showcase"
